version: '3'

services:
  # Servicio para ejecutar las pruebas del frontend
  frontend-test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    volumes:
      - ./cliente/src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./vite.config.mts:/app/vite.config.mts
      - ./vitest.config.ts:/app/vitest.config.ts
      - ./.eslintrc.cjs:/app/.eslintrc.cjs
      # Asegurar que los archivos de test se copian correctamente
      - ./cliente/src/__tests__:/app/src/__tests__ 