# docker-compose.yml
version: '3.8'

services:
  lcln-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./config_lynx.json:/app/config_lynx.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # MySQL para base de datos (opcional - para producción)
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: lynx_root_2025
      MYSQL_DATABASE: lynx_products
      MYSQL_USER: lynx_user
      MYSQL_PASSWORD: lynx_pass_2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
